const List = [
    {
        id:0,
        propName:"购买方式",
        options:[{
            value:"按课时购买",
            checked:false
        },{
            value:"包月购买",
            checked:false
        },{
            value:"团体购买",
            checked:false
        }]
    },
    {
        id:1,
        propName:"上课类型",
        options:[{
            value:"1v1",
            checked:false
        },{
            value:"1v3",
            checked:false
        },{
            value:"1v6",
            checked:false
        }]
    },{
        id:2,
        propName:"购买时长",
        options:[{
            value:"1个月",
            checked:false
        },{
            value:"3个月",
            checked:false
        },{
            value:"6个月",
            checked:false
        },{
            value:"1年",
            checked:false
        }]
    },{
        id:3,
        propName:"购买课时数",
        options:[{
            value:"100课时",
            checked:false
        },{
            value:"200课时",
            checked:false
        },{
            value:"300课时",
            checked:false
        }]
    },
]
export default List