const fileFormat ={
    dir:"/assets/folder.svg",
    edb:"/assets/eeo.svg",
    edt:"/assets/eeo.svg",
    pptx:"/assets/ppt.svg",
    ppt:"/assets/ppt.svg",
    pptm:"/assets/ppt.svg",
    doc:"/assets/word.svg",
    docx:"/assets/word.svg",
    pdf:"/assets/pdf.svg",
    jpeg:"/assets/jpg.svg",
    jpg:"/assets/jpg.svg",
    png:"/assets/jpg.svg",
    bmp:"/assets/jpg.svg",
    mp3:"/assets/audio.svg",
    wav:"/assets/audio.svg",
    wma:"/assets/audio.svg",
    aac:"/assets/audio.svg",
    flac:"/assets/audio.svg",
    m4a:"/assets/audio.svg",
    oga:"/assets/audio.svg",
    mp4:"/assets/video.svg",
    mpg:"/assets/video.svg",
    mpeg:"/assets/video.svg",
    avi:"/assets/video.svg",
    flv :"/assets/video.svg",
    h264:"/assets/video.svg",
    m4v :"/assets/video.svg",
    mj2:"/assets/video.svg",
    mov:"/assets/video.svg",
    ogg :"/assets/video.svg",
    ogv :"/assets/video.svg",
    rm :"/assets/video.svg",
    qt :"/assets/video.svg",
    vob :"/assets/video.svg",
    webm :"/assets/video.svg",
    "3gp":"/assets/video.svg",
    "3g2":"/assets/video.svg",
    txt :"/assets/txt.svg",
    html :"/assets/txt.svg",
    htm  :"/assets/txt.svg",
    css  :"/assets/txt.svg",
    js :"/assets/txt.svg",
    as :"/assets/txt.svg",
    cpp :"/assets/txt.svg",
    c :"/assets/txt.svg",
    cc :"/assets/txt.svg",
    cxx :"/assets/txt.svg",
    h :"/assets/txt.svg",
    java :"/assets/txt.svg",
    md :"/assets/txt.svg",
    matlab :"/assets/txt.svg",
    pascal :"/assets/txt.svg",
    pl :"/assets/txt.svg",
    php :"/assets/txt.svg",
    py :"/assets/txt.svg",
    r :"/assets/txt.svg",
    rb :"/assets/txt.svg",
    ru :"/assets/txt.svg",
    sql :"/assets/txt.svg",
    swift :"/assets/txt.svg"
}
export default fileFormat;